package main

import (
	"encoding/base64"
	"fmt"
	"math/rand"
	"time"
)

var kurcevi = []string{
	"ICAgICAgICAgICAgICAgICAgICAgICAgXywtJS8lfAogICAgICAgICAgICAgICAgICAgIF8sLScgICAgXC8vJVwKICAgICAgICAgICAgICAgIF8sLScgICAgICAgIFwlL3wlCiAgICAgICAgICAgICAgLyAvICkgICAgX18sLS0gIC8lXAogICAgICAgICAgICAgIFxfXy9fLC0nJSglICA7ICAlKSUKICAgICAgICAgICAgICAgICAgICAgICVcJSwgICAlXAogICAgICAgICAgICAgICAgICAgICAgICAnLS0lJyAgICAgICAgIAoKCg==",
	"ICAgICAgX19fCiAgICAgLy8gIDcKICAgIChfLF8vXAogICAgIFwgICAgXAogICAgICBcICAgIFwKICAgICAgX1wgICAgXF9fCiAgICAgKCAgIFwgICAgICkKICAgICAgXF9fX1xfX18vICAKCg==",
	"4paR4paR4paE4paE4paR4paR4paR4paR4paE4paR4paR4paR4paR4paE4paR4paR4paRIArilpHilpHilpHilpHilpHilpHilojiloTilpHilpHilpHilojilpHilpHilojiloDilpHilpHilpHilpEgCuKWkeKWkeKWkeKWkeKWkeKWkeKWkeKWgOKWiOKWhOKWkeKWgOKWkeKWkeKWkeKWkeKWkeKWkeKWkeKWkSAK4paR4paR4paR4paR4paE4paR4paR4paR4paE4paE4paI4paI4paI4paE4paR4paR4paR4paE4paE4paRIArilpHilpHilpHiloDiloDilpHilpHiloTilojilpHilpHilojilpHilojiloTilpHilpHilpHiloDiloggCuKWkeKWkeKWkeKWkeKWkeKWkeKWkeKWiOKWkeKWkeKWkeKWkeKWkeKWkeKWiOKWkeKWkeKWkeKWkeKWkSAK4paR4paR4paR4paR4paR4paR4paR4paI4paI4paI4paI4paI4paI4paI4paI4paR4paR4paR4paR4paRIArilpHilpHilpHilpHilpHilpHilpHilojiloTiloTilpHilpHilpHilpHilojilpHilpHilpHilpHilpEgCuKWkeKWkeKWkeKWkeKWkeKWkeKWkeKWiOKWkeKWkeKWkeKWkeKWgOKWgOKWiOKWkeKWkeKWkeKWkeKWkSAK4paR4paR4paR4paR4paR4paR4paR4paI4paA4paA4paA4paR4paE4paE4paI4paR4paR4paR4paR4paRIArilpHilpHilpHilpHilpHilpHilpHilojilpHilpHilpHilpHiloDiloDilojilpHilpHilpHilpHilpEgCuKWkeKWkeKWkeKWkeKWkeKWkeKWkeKWiOKWgOKWgOKWgOKWkeKWhOKWhOKWiOKWkeKWkeKWkeKWkeKWkQrilpHilpHilpHilpHilpHilpHilpHilojilpHilpHilpHilpHilpHilpHilojiloTilpHilpHilpHilpEgCuKWhOKWhOKWhOKWhOKWiOKWiOKWgOKWgOKWkeKWkeKWkeKWkeKWkeKWkeKWkeKWgOKWiOKWiOKWkeKWkSAK4paR4paE4paI4paA4paR4paA4paR4paR4paR4paR4paE4paR4paR4paR4paR4paR4paR4paI4paE4paEIAriloDiloDilojiloTiloTiloTilpHilpHilpHiloTilojilojilpHilpHilpHilpHiloTilojilpHilpEgCuKWkeKWiOKWgOKWiOKWhOKWhOKWhOKWhOKWiOKWgOKWkeKWiOKWiOKWhOKWhOKWiOKWiOKWhOKWhOKWkSAK4paR4paR4paR4paR4paA4paR4paR4paR4paA4paR4paR4paR4paA4paR4paR4paR4paR4paR4paR4paRCg==",
}

// Main
func main() {
	rand.Seed(time.Now().Unix())
	n := rand.Int() % len(kurcevi)
	// fmt.Println(n)
	decoded, err := base64.StdEncoding.DecodeString(kurcevi[n])
	if err != nil {
		fmt.Println("error:", err)
		return
	}
	fmt.Printf("%s", decoded)
}
